### PR TITLE
command line utils refurbished

### PR DESCRIPTION
**Pull request by r3wald**
For sml_server you now have the possibility to choose a device to read from. And I added a simple parser for binary dumps (see http://www.github.com/devZer0/libsml-testing).

### CODE REVIEW

**Comment by andig** [comment]
Ping @mbehr1 ok to merge?

**Comment by andig** [comment]
ping @hmmueller would this PR be something you could review and potentially fix? Unfortunately we're a bit short on C developers.

**Comment by hmueller01** [comment]
This was partially addressed by my pull #21. I will look intro this and will see how I can merge some good things of @r3wald  into master.

**Comment by hmueller01** [comment]
Ok, looked into this. As github states, this conflicts with the current master. I can not resolve this, because I do not have write access to this repository. Maybe @r3wald can resolve this and I can review.

**Comment by andig** [comment]
> I can not resolve this, because I do not have write access to this repository.

@hmueller01 you can checkout r3wald's branch just like any other one, make changes and push to your repository, then create a PR. See https://stackify.com/git-checkout-remote-branch/

**Comment by andig** [comment]
Superceeded by#28

**Pull request closed without merging**
