### PR TITLE
Rename server to parser

### PR DESCRIPTION
**Pull request by andig**
plus minor code changes

### CODE REVIEW

**Comment by hmueller01** [comment]
I personally do not like the name change. I (and maybe others) need to update all my dependencies on other projects and on my RaspberryPi(s). As said in #33 it is as much a server as it is a parser. It is somehow both, so why the change?

**Comment by devZer0** [comment]
i would vote for the change but if it would hurt holger too much, i would say lets keep it as is for now because of his intervention, but lets introduce a transioning phase. what about creating two binaries for a while or announcing a future rename wirh a message on build?

could you live with such, holger?

**Comment by andig** [comment]
Its probably not best practice to rely on files in the examples folder but anyway...

**Comment by hmueller01** [comment]
Yes that is true in deed. Should we build a parser in another subdir and stop working on the example?

**Comment by hmueller01** [comment]
Is there a wish to start a "real" parser and keep example as it is? If not I would like to add more features to example/sml_server.c

**Pull request closed without merging**
