### PR TITLE
Debian changes

### PR DESCRIPTION
**Pull request by narc-Ontakac2**
These are changes that were in the debian branch but can as well be applied to the master and changes that will help me doing official Debian releases. 

I am doing this because I found using a single debian branch for all official Debian releases unmaintainable. Disadvantage of this approach is that I will create one debian-<debian version> branch for every official Debian release. I hope this is acceptable.

If this works well I will do the same for vzlogger.

### CODE REVIEW

**Comment by r00t-** [comment]
what was the reason not to do the packages straight off master?

**Comment by narc-Ontakac2** [comment]
This is because the Debian package should not be a native package, see https://www.debian.org/doc/debian-policy/ch-source.html. This is not against Debian policy, but Debian developers generally advise against it. 

There are several reasons:
1. Our packages are signed with a key that is uploaded to Github. For a Debian release it has to be signed with my Debian maintainer key that I consider very sensitive and that I will not upload to Github.
2. Our package gets a different version number than the Debian package. This can be helpful in case of stupid packaging mistakes that are only relevant for Debian.
3. The Debian package has slightly more modern settings in Debian control since it is only menat for Trixie. This will be more relevant for vzlogger because there will be a dependeny on openssl >= 3.0. This makes builds for buster impossible.

**Comment by narc-Ontakac2** [comment]
Are these good reasons or do you object to a merge?

**Comment by r00t-** [comment]
i'm not objecting to a merge at all.
i was only asking why you maintain a separate debian branch at all.
feel free to merge as you see fit.

**Pull request merged**
