### PR TITLE
 added make install target as requested by #14 

### PR DESCRIPTION
**Pull request by hmueller01**
added make "install" and "uninstall" target as requested by #14

### CODE REVIEW

**Comment by andig** [comment]
ping @r00t- can I ask you for review? This is beyond my skill level ;)

**Comment by andig** [comment]
@hmueller01 you would typically create a single branch from master per PR to keep things separated, Since the others have been merged though this is not necessary here- thanks!

**Comment by andig** [comment]
ping @ampelbein could I ask you for review here?

**Comment by hmueller01** [comment]
@andig I do not know how to do that. I fetched upstream and merged with my fork. After that I made my changes, committed and push to my fork. After that I issued a new pull request. The diff is correct, but the change log is not. I do not know how to avoid this.

**Comment by andig** [comment]
>  I do not know how to do that. I fetched upstream and merged with my fork. After that I made my changes, committed and push to my fork. 

@hmueller01 check out https://guides.github.com/introduction/flow/ 

The idea is that you *never* work in master (it's just a copy of this repo's master) and perform all work in branches. To create a branch: `git checkout -b cooles_feature`. Send branch to your GH repository: `git push -u origin cooles_feature`. At this point you can create PRs for this repo per branch.

**Pull request merged**
