### PR TITLE
[peterevertz] Fix for different timestamp sent by some meters

### PR DESCRIPTION
**Pull request by r00t-**
"some meters (FROETEC Multiflex ZG22) giving not one uint32 as timestamp, but a list of 3 values.
Ignoring these values, so that parsing did not fail.

Added a simple "make install"
Add some code to the example programm: can read a file, and give some more verbose output."

https://github.com/dailab/libsml/pull/6

### CODE REVIEW

**Comment by andig** [comment]
+1 - suggesting to apply for the benefit of `make install`

**Comment by r00t-** [comment]
the implementation of the install target is rather basic/primitive.
(using only "cp", ... also surpressing messages with @ (copied from "clean" above?)
is it a good idea to include it like that?

**Comment by andig** [comment]
Why are all 3 tuples ignored? Shouldn't one of those be the actual timestamp?

**Comment by andig** [comment]
Ping @peterevertz

**Comment by peterevertz** [comment]
I was working on libsml to get it working with vzlogger. Without my "ignore patch" libsml just runs into an error, not getting any data from frontek meters. Because vzlogger create own timestamps, the meter timestamp is just ignored. 
I have no information how the timestamp is formated, and if it is to be trusted. Timestamps are important to match with vzlogger, otherwise you get peaks and others problems.

**Comment by andig** [comment]
Could you try to log the 3 values in the list and see if one of those is actually the desired timestamp? If yes it might make more sense to use that as timestamp rather than to skip all three values?

**Comment by andig** [comment]
Make replaced by #24

**Comment by hmueller01** [comment]
This pull request includes lots of things in one. I learned that this is no good idea. :-)
Is there a binary dump of this power meter, that we can reproduce the error?

**Comment by andig** [comment]
@peterevertz laut PR scheint der erste Wert aus dem `LIST[3]` ein `u32` zu sein- wie ein normaler Timestamp auch. Hast Du evtl. mal geschaut ob es sich bei diesem `u32` um einen Timestamp handelt?

Wäre es sinnvoll auszuprobieren ob wir- statt alle Werte zu verwerfen- `LIST[0]` als Timestamp nehmen können? Damit wäre der Fehler beim Parsing behoben und es gäbe weiter Timestamps vom Gerät.

Meinungen?

**Comment by peterevertz** [comment]
@andig I do not have such a meter. And as i said 2016: I would not trust and use timestamps from meters. My goal was to make these Frotec meters usable with vzlogger not more, note less.

**Comment by hmueller01** [comment]
@r00t- Do you have such a meter and can provide a bin dump for testing?

**Comment by r00t-** [comment]
@hmueller01:
none of this is my code, i only created a PR for @peterevertz's patches, he has the meter, i don't.

**Comment by hmueller01** [comment]
Ok, if no one has such a meter we can not change this without any testing. Should we close this for now without merging?

**Comment by r00t-** [comment]
@hmueller:
while not accepting the change may be right from a general project management approach,
i think for the purposes of volkszaehler.org, the change would be an improvement even without being properly tested.
given my experience with our userbase, it is very unlikely that the next user to have such a meter will be competent enough to provide a dump or test a development version, or even file a bug report.
as long as the change does not cause any harm, we should rather accept it and ship it, so it will be available to future users of that meter immediately.
(we do need to extract the feature from this shared PR, i might do that later.)

**Comment by hmueller01** [comment]
Agreed. Just as it is, without the wish of @andig to interpret the values (as we can not test this). This is in deed a good improvement.
@r00t- will you do resolve the conflicts or shall I?

**Comment by r00t-** [comment]
it's more than resolving conflicts i think, the commit cobtains lots of unrelated changes and needs some careful analysis.
as i said, i might do this later, but i won't complain if you do it.
(the commit is four years old, i see no need to hurry...)

**Comment by hmueller01** [comment]
@r00t- You are right. There is more work removing all the not needed stuff. If no one disagrees I will make an new pull request with only the sml_time.c fix, which is pretty easy.

**Comment by peterevertz** [comment]
@hmueller01 That is is a good decision. I mixed up many changes in vzlogger and libsml because the whole project was a mostly crashing mess when i startet to contribute. Not a good style, i know....

**Comment by andig** [comment]
Replaced by #37

**Pull request closed without merging**
